package main

import (
	"testing"
	"fmt"
)

var ref string = "CACATGGAATTAGGCCAGTAGTATCAACTCAACTGCTGTTAAATGGCAGTCTAGCAGAAGAAGAGGTAGTAATTAGATCTGCCAATTTCACAGACAATGCTAAAACCATAATAGTACAGCTGAACCAATCTGTAGAAATTAATTGTACAAGACCCAACAACAATACAAGAAAAAGAATCCGTATCCAGAGGGGACCAGGGAGAGCATTTGTTACAATAGGAAAAATAGGAAATATGAGACAAGCACATTGTAACATTAGTAGAGCAAAATGGAATGCCACTTTAAAACAGATAGCTAGCAAATTAAGAGAACAATTTGGAAATAATAAAACAATAATCTTTAAGCAATCCTCAGGAGGGGACCCAGAAATTGTAACGCACAGTTTTAATTGTGGAGGGGAATTTTTCTACTGTAATTCAACACAACTGTTTAATAGTACTTGGTTTAATAGTACTTGGAGTACTGAAGGGTCAAATAACACTGAAGGAAGTGACACAATCACACTCCCATGCAGAATAAAACAATTTATAAACATGTGGCAGGAAGTAGGAAAAGCAATGTATGCCCCTCCCATCAGCGGACAAATTAGATGTTCATCAAATATTACAGGGCTGCTATTAACAAGAGATGGTGGTAATAACAACAATGAGTCCGAGATCTTCAGACCTGGAGGAGGAGATATGAGGGACAATTGG"
var sr string = "AAAAGAACAACTTGGAAATAAAACAATAGTCTTTAATCAATCCTCAGGAGGGGACCCAGAAATTGTACTGCACAATTTTAATTGTAGAGGGGAATTTTTCTACTGTAATCTATCGCAACTGTTTAATTGGACAGATAATGAGGCTTGGAGTAATGAAACCTATACTACTGACACTGTGATAGTGTCAGTAGTATTGGTTTCATTACTCCAAGCCTCATTATCTGTCCAATTAAACAGTTGCGATAGATTACAGTAGAAAAATTCCCCTCTACAATTAAAATTGTGCAGTACAATTTCTGGGTCCCCTCCTGAGGATTGATTAAAGACTATTGTTTTATTTCCAAGTTGTT"
func TestGetFuzzy(t *testing.T) {
	// fmt.Println("asdfasdf")
}


func TestExtendHead(t *testing.T) {
	var start int
	srPos := 184
	refPos := 14
	k := 8
	window := 5
	thres := 3

	start = extendHead(sr, &ref, srPos, refPos, k, thres, window)

	fmt.Println(start)
}

func BenchmarkExtendHead(b *testing.B) {
	var start int
	srPos := 184
	refPos := 14
	k := 8
	window := 5
	thres := 3

    b.ResetTimer()
	for i := 0; i < b.N; i++ {
        start = extendHead(sr, &ref, srPos, refPos, k, thres, window)
    }
	fmt.Println(start)
}


// func TestExtendTail(t *testing.T) {
// 	var wg sync.WaitGroup
// 	var end int
// 	wg.Add(1)
// 	srPos := 28
// 	refPos := 215
// 	k := 8
// 	window := 8
// 	thres := 5

// 	go func() {
// 		end = extendTail(sr, &ref, srPos, refPos, k, thres, window)
// 	}()
// 	wg.Wait()
// 	fmt.Println(end)
// }

func TestReverse(t *testing.T) {
	reverse := reverse("abcdefg")
	// t.Log(reverse)
	fmt.Println(reverse)
}